name: Performance Tests LMS
on:
  push:
    branches:
      - main
jobs:
  performance_tests:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install K6 (for performance testing)
      - name: Install K6 via Snap
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo snap install k6

      # 3. Create directory for k6 results
      - name: Create k6 results directory
        run: mkdir -p results

      # 4. Run performance test with k6 and save results
      - name: Run K6 Performance Test
        run: |
          k6 run scripts/load-test.js --out json=results/results.json

      # 5. Publish k6 results as GitHub Actions artifacts
      - name: Upload K6 Results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ./results/