name: Performance Tests LMS
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install K6
        run: |
          sudo apt update
          sudo apt install -y k6

      - name: Run performance tests
        run: |
          k6 run performance-test-lms/scripts/load-test.js